version: "3"

services:
   stackdrive-agent:
      image: ${registry_repository}/${image_name}:${image_ver}
      container_name: stackdriver-agent
      mem_limit: 250m
      mem_reservation: 150m
      security_opt:
         - apparmor=unconfined
      cap_add:
         - SYS_PTRACE
         - SYS_ADMIN
         - NET_ADMIN
      pid: host
      entrypoint:
         - /entrypoint.sh
      environment:
         - SSH_AUTH_SOCK
         - SSH_TTY
         - SSH_CLIENT
         - SSH_CONNECTION
         - GOOGLE_APPLICATION_CREDENTIALS=${gapp_cred}
      restart: unless-stopped
      volumes:
         - ${gapp_cred}:${gapp_cred}
